credentials:
  usernames:
    guest:
      email: guest@veekstar.com
      name: Demo Reviewer
      password: '$2b$12$3vZ8.v02SBVZ5sKFHpgMiu0tchgl./xHtF8tHWfPBJEDix3/eB6li'  # password = veekstar2025

cookie:
  name: veekstar_cookie
  key: veekstar_key
  expiry_days: 1

preauthorized:
  emails:
    - guest@veekstar.com